spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: root
    password: password

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

#springdoc:
#  version: '@springdoc.version@'
#  swagger-ui:
#    display-request-duration: true
#    groups-order: DESC
#    operationsSorter: method
#    disable-swagger-default-url: true
#    use-root-path: true
#  show-actuator: true
#  group-configs:
#    - group: product
#      paths-to-match: /product/**

server.port: 8080